### ISSUE TITLE
Create a function to return the eigenvectors to be used in reducing the dimensions. 

### ISSUE THREAD

**Issue by StephenNu** [StephenNu/HDA#10]
# Summary

Use the function designed in [issue 9](https://github.com/StephenNu/HDA/issues/9) to sum all the terms, and gather the solution when done, change the dataset to rely on its new lower dimensional space.
# Details

We need to convert the passed in dataset to a lower dimensional space, this is by solving the equation given in [this google doc](https://docs.google.com/document/d/1nca333-gZOrJXLlRfdXr1nzC-cVjrtimUrPoEmBYWqQ/edit?usp=sharing), once we do so we convert the dataset to the lower space.
# Todo
- Loop over all values of i and j, to construct the matrix which will contain the solution.
- Find its eigenvalues, and use them as described in uwindsor's 473 courseware, chapter 8 slide 32-33.
- Once this is complete, correct [issue 1](https://github.com/StephenNu/HDA/issues/1)

**Comment by Yuwain** [comment]
my b

**Comment by StephenNu** [comment]
This is for the entire solution, and should return the _d_ eigenvectors associated with the _d_ maximum eigenvalues.
