### ISSUE TITLE
Create a function to reduce the dataset

### ISSUE THREAD

**Issue by StephenNu** [StephenNu/HDA#45]
# Summary

We need a function that given a list of instances Inst, and a matrix A, return a matrix A*Inst.
# Details

This will reduce the original inputted data to the dimensions we are reducing to. This matrix A is the matrix returned by #10. 
# Todo
- Get the matrix A from the function solution (Issue #10)
- Convert the Instances Inst, into a matrix (ensure that the class label is not in the matrix)
- Perform the multiplication and return the result

**Comment by Yuwain** [comment]
Breaking this into two issues for consistency.
