### ISSUE TITLE
Construct the combined scatter matrices

### ISSUE THREAD

**Issue by StephenNu** [StephenNu/HDA#5]
# Summary

We need to combined the already implemented scatter matrices, of two classes, so we can support datasets with more than two classes.
# Details

We define the combined scatter matrices to be **S<sub>ij</sub>** = π<sub>ij</sub>S<sub>i</sub> + π<sub>ji</sub>S<sub>j</sub>. Where π<sub>ij</sub> is defined as in [issue 4](https://github.com/StephenNu/HDA/issues/4)
# Todo
- Create a function to return a list of combined scatter matrices such that list[i][j] = **S<sub>ij</sub>**

**Comment by StephenNu** [comment]
So you know if you wrote Fixes #5 rather then Issue #5, this would be automagically closed.

**Comment by Yuwain** [comment]
:'c

**Comment by StephenNu** [comment]
Don't feel bad my first one didn't automagically close either, but then I knew I heard of people who had it close on a merge so I looked it up lol
