### ISSUE TITLE
Taking log/sqrt of negative Numbers, causes matrix to be filled with NaN

### ISSUE THREAD

**Issue by StephenNu** [StephenNu/HDA#56]
When using weka, change the number of attributes to 5 in the data generation tool. This causes a distribution of data points that involves negative numbers, both Log and Sqrt are undefined on negative values, this results in NaN being placed into the matrix.

The result is Weka freezes waiting for the eigenvalue decomposition to return.

**Comment by Yuwain** [comment]
Throwing an exception when trying to parse a negative eigenvalue. Maybe one day Java will figure out complex numbers.
