### ISSUE TITLE
Will not compile with stable book version of Weka (3.6)

### ISSUE THREAD

**Issue by StephenNu** [StephenNu/HDA#58]
# Description

When I was installing on my Linux Mint system to ensure that my build steps in the README was correct. I noticed that I needed not the stable version which mint installed with, 

```
sudo apt-get install weka
```

but rather the development version. Which meant I had to go download the zip file myself and extract it.

My question is, can we remove any dependencies on the development version so we work with the stable version of weka that I would assume most linux systems default install.

Both versions can be found on their [website](http://www.cs.waikato.ac.nz/ml/weka/downloading.html)

**Comment by StephenNu** [comment]
From further reading it seems like there is no package manager in weka version (< 3.7.2) so even if we didn't you wouldn't be able to use it. I will do more research, and if that remains true we can just close this issue.

**Comment by roederw** [comment]
I ran into this issue as well. Using Homebrew it installed a 3.6.x version that does not have a package manager. Meaning, I had to manually get Weka and unzip it. I have a feeling there isn't anything we can do.
